--CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
--INSERT INTO Cliente(id,nome) VALUES (nextval('hibernate_sequence'),'Joao');
--INSERT INTO Cliente(id,nome) VALUES (nextval('hibernate_sequence'),'Maria');
--INSERT INTO Cliente(id,nome) VALUES (nextval('hibernate_sequence'),'Jose');
--INSERT INTO Cliente(id,nome) VALUES (nextval('hibernate_sequence'),'Ana');
INSERT INTO Cliente(id,nome) VALUES (1,'Joao');
INSERT INTO Cliente(id,nome) VALUES (2,'Maria');
INSERT INTO Cliente(id,nome) VALUES (3,'Jose');
INSERT INTO Cliente(id,nome) VALUES (4,'Ana');
--CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;
--INSERT INTO Cliente(nome) VALUES ('Joao');
--INSERT INTO Cliente(nome) VALUES ('Maria');
--INSERT INTO Cliente(nome) VALUES ('Jose');
--INSERT INTO Cliente(nome) VALUES ('Ana');
